### ISSUE TITLE
New Riot Client update moved the login button, swap to press enter?

### ISSUE THREAD

**Issue by HiroLeWeeb** [sidit77/LoLAccountManager#1]
I believe the new Riot Client came out for 11.21 or mid-patch and it moved the login button (again), which leaves the autofill part still working.
Is it better to swap the mouse interaction for login button to a simple enter key input or to change mouse click coordinates?

**Comment by sidit77** [comment]
> I believe the new Riot Client came out for 11.21 or mid-patch and it moved the login button (again), which leaves the autofill part still working.

Yeah, I've noticed the change yesterday and planed on fixing it today.

> Is it better to swap the mouse interaction for login button to a simple enter key input or to change mouse click coordinates?

Originally autofill worked by bringing the client to the front and then pressing <tab> once to select the username, once more to select the password and so on. The problem with this strategy was that it depended on which element was initially focused and therefore failed quite often.
I was/am honestly quite happy with the click-the-fields approach but the constant breaking gets annoying. My current standpoint is to keep fixing it for now and hope that Riot stops moving stuff around. However I'm open to go back to tabbing if it keeps breaking. Also it's a pretty good idea to replace the login click with a simple enter for now and see if it works consistently. I will include this in the next update.

**Comment by sidit77** [comment]
Update:
Your enter key suggestions works great. After some testing I've also swapped back to using tab presses.

**Comment by HiroLeWeeb** [comment]
New update works great, thanks !
But why is the 1.8-gh2 almost 90MB? Is it containing .NET 5 installer just in case the computer doesn't have it installed?

**Comment by sidit77** [comment]
Kinda. When you publish a .NET 5 app you can choose to build the app as a standalone exe, where all necessary parts of the .NET runtime are bundled into the exe itself. This means the it's not necessary to ensure that the user has the right runtime installed at the cost of some additional disk space. I think that this tradeoff is worth it, especially because this seems to be the recommend way to distribute your app.

**Comment by HiroLeWeeb** [comment]
> When you publish a .NET 5 app you can choose to build the app as a standalone exe, where all necessary parts of the .NET runtime are bundled into the exe itself.

That's a cool feature.
Anyway thanks for the update once again !

**Comment by HiroLeWeeb** [comment]
Ironically enough, it worked a few hours ago but tried right now and Riot again decided to do some client magic and now it just clicks on the middle and doesn't do anything. 
Tried redownloading both lightweight and standalone version, restarting both client and PC, no luck.

**Comment by sidit77** [comment]
Do you still have the problem after a client or computer restart? At least for me it's still working.

**Comment by HiroLeWeeb** [comment]
> Do you still have the problem after a client or computer restart? At least for me it's still working.

No it started working again, weird.
